wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722614700
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.12.4
      5: 0.17.5
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.001
gamma:
  desc: null
  value: 0.99
buffer_limit:
  desc: null
  value: 20000
